# Built with Jekyll 3.2.0 and Ed.

# Setup
title:               Trianam's notes
tagline:             'a blog about machine learning and artificial intelligence'
description:         'By Stefano Martina'
url:                 'https://trianam.github.io'
baseurl:             ''

# About/contact
author:
  name:              Stefano Martina
  url:               http://ai.dinfo.unifi.it/stefano
  email:             

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
#collections_dir: collections
collections:
  theory:
    output: true
    weight: 10
    title: "Theory"
    order:
      - '/theory/linear-algebra'
      - '/theory/machine-learning'
      - '/theory/graphical-models'
  ml:
    output: true
    weight: 20
    title: "Machine Learning"
    order:
      - '/ml/hyperparameters-optimization'
  
  nn:
    output: true
    weight: 40
    title: "Neural Networks"
    order:
      - '/nn/autoencoders'
      - '/nn/rnn'
      - '/nn/cascade-correlation'

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
#theme: "ed."


